name: Windows x86-64 MSYS2 MinGW UCRT64
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-make

      - name: Checkout libncore code
        uses: actions/checkout@v4
        with:
          repository: RomanDonw/libncore
          path: libncore

      - name: Setup dependencies
        shell: msys2 {0}
        run: |
            cd libncore

            mkdir build
            cd build

            cmake -S .. -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$MSYSTEM_PREFIX -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
            mingw32-make install

            cmake -S .. -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=$MSYSTEM_PREFIX -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
            mingw32-make install

      - name: Configure and Build
        shell: msys2 {0}
        run: |
          mkdir build
          cd build

          cmake -S .. -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$MSYSTEM_PREFIX -DCMAKE_BUILD_TYPE=Release
          mingw32-make install
          
          cmake -S .. -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=$MSYSTEM_PREFIX -DCMAKE_BUILD_TYPE=Release
          mingw32-make install

          cd ..

          mkdir bin
          mv build/*.dll bin/

          mkdir lib
          mv build/*.a lib/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win64-mingw-ucrt64
          path: |
            bin/*.dll
            lib/*.a
            include/*.h